### ISSUE TITLE
windows fatal exception: access violation crashing QGIS entirely

### ISSUE THREAD

**Issue by e-shirt** [Ludwig-K/QGisLinearReference#3] opened 2023-07-20 12:34 UTC
Found another bug, that fully crashes QGIS. Happened when trying to insert a LoL feature.

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x00001884 (most recent call first):
  File "C:\Users/Eschert/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LinearReferencing\map_tools\LolEvt.py", line 1061 in set_edit_pk
    self.ds.dataLyr.select(data_feature.id())
  File "C:\Users/Eschert/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LinearReferencing\map_tools\LolEvt.py", line 3492 in s_insert_feature
    self.set_edit_pk(used_pk, False)
```

**Stack Trace**

```

QSortFilterProxyModel::parent :
QModelIndex::parent :
QTableView::visualRect :
QAbstractItemView::updateEditorGeometries :
QAbstractItemView::updateGeometries :
QTableView::updateGeometries :
QAbstractItemView::doItemsLayout :
QTableView::doItemsLayout :
QTableView::visualRect :
QAbstractItemView::update :
QgsFeatureListView::repaintRequested :
QObject::qt_static_metacall :
QgsFeatureSelectionModel::requestRepaint :
QgsFeatureSelectionModel::layerSelectionChanged :
QObject::qt_static_metacall :
QgsIFeatureSelectionManager::selectionChanged :
QObject::qt_static_metacall :
QgsVectorLayer::selectionChanged :
QgsVectorLayer::select :
pdal::MetadataNode::value :
PyArg_ParseTuple_SizeT :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyFloat_FromDouble :
PyEval_EvalFrameDefault :
PyFunction_Vectorcall :
PyFloat_FromDouble :
PyVectorcall_Call :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QObject::qt_static_metacall :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
PyInit_QtWidgets :
QWidget::event :
PyInit_QtWidgets :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.32.0-Lima
QGIS code revision: 311a8cb8a6
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.7.0
Running against GDAL: 3.7.0

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

**Comment by Ludwig-K** [comment] 2023-07-20 21:18
I could not reproduce this error, possibly it was caused by issue #2 and is also fixed.
The new plugin version 1.0.2 must be approved and should be downloadable soon.
Please test yourself and close this issue if successful.

**Closed as completed** 2023-07-22 20:40 UTC
